# Generated by Django 3.2.6 on 2021-08-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_auto_20210822_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='advertise',
            options={'verbose_name_plural': 'Advertise'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name_plural': 'Privacy'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
    ]
